version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app/reporter
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install && ls -l node_modules
      - run: pwd && ls -la
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/app
          paths:
            - reporter
  report-order:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app/reporter
    steps:
      - attach_workspace:
          at: ~/app
      - run: pwd && ls -la
      - run:
          name: Fetch ORDER data, create xlsx and send mail
          command: yarn order:ci

  report-product:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app/reporter
    steps:
      - attach_workspace:
          at: ~/app
      - run: pwd && ls -la
      - run:
          name: Fetch PRODUCT data, create xlsx and send mail
          command: yarn product:ci

  report-category:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app/reporter
    steps:
      - attach_workspace:
          at: ~/app
      - run: pwd && ls -la
      - run:
          name: Fetch CATEGORY data, create xlsx and send mail
          command: yarn category:ci

workflows:
  version: 2
  Orders Report:
    triggers:
      - schedule:
          cron: '0 2 * * *'
          filters:
            branches:
              only: master
    jobs:
      - build
      - report-order:
          requires:
            - build

  Product Report:
    triggers:
      - schedule:
          cron: '0 2 * * 1'
          filters:
            branches:
              only: master
    jobs:
      - build
      - report-product:
          requires:
            - build

  Category Report:
    triggers:
      - schedule:
          cron: '0 2 * * 1'
          filters:
            branches:
              only: master
    jobs:
      - build
      - report-category:
          requires:
            - build
